/**
 * prismjs-components 的类型声明
 * prismjs 的组件文件（.min.js）是 side-effect 模块，导入后自动注册语言到 Prism.languages。
 * TypeScript 需要这个声明来避免 "Could not find a declaration file" 错误。
 */
declare module 'prismjs/components/prism-typescript.min.js'
declare module 'prismjs/components/prism-javascript.min.js'
declare module 'prismjs/components/prism-tsx.min.js'
declare module 'prismjs/components/prism-jsx.min.js'
declare module 'prismjs/components/prism-python.min.js'
declare module 'prismjs/components/prism-rust.min.js'
declare module 'prismjs/components/prism-go.min.js'
declare module 'prismjs/components/prism-java.min.js'
declare module 'prismjs/components/prism-c.min.js'
declare module 'prismjs/components/prism-cpp.min.js'
declare module 'prismjs/components/prism-csharp.min.js'
declare module 'prismjs/components/prism-ruby.min.js'
declare module 'prismjs/components/prism-bash.min.js'
declare module 'prismjs/components/prism-powershell.min.js'
declare module 'prismjs/components/prism-yaml.min.js'
declare module 'prismjs/components/prism-json.min.js'
declare module 'prismjs/components/prism-markup.min.js'
declare module 'prismjs/components/prism-css.min.js'
declare module 'prismjs/components/prism-scss.min.js'
declare module 'prismjs/components/prism-sql.min.js'
declare module 'prismjs/components/prism-markdown.min.js'
declare module 'prismjs/components/prism-diff.min.js'
declare module 'prismjs/components/prism-docker.min.js'
declare module 'prismjs/components/prism-graphql.min.js'
declare module 'prismjs/components/prism-toml.min.js'
declare module 'prismjs/components/prism-kotlin.min.js'
declare module 'prismjs/components/prism-scala.min.js'
declare module 'prismjs/components/prism-swift.min.js'
declare module 'prismjs/components/prism-php.min.js'
declare module 'prismjs/components/prism-latex.min.js'
declare module 'prismjs/components/prism-ini.min.js'
declare module 'prismjs/components/prism-makefile.min.js'
